sudo: required
language: node_js

node_js:
  - "8"

before_script:
  - curl https://install.meteor.com/ | sh
  - meteor npm install
  - meteor npm install -g reaction-cli
  - sudo chown travis -R -h -v .meteor/local /home/travis/.config

script:
  - reaction test

notifications:
  slack: olgaverkkokauppa:VyuKQR5JBQpHmyOWE6bPRBZp