sudo: required
language: node_js

node_js:
  - "7"

before_script:
  - npm install
  - npm install -g reaction-cli
  - curl https://install.meteor.com/ | sh
  - sudo meteor npm install
  - sudo chown travis -Rh .meteor/local /home/travis/.config
  - meteor update --release 1.5.1


script:
  - reaction test

notifications:
  slack: olgaverkkokauppa:VyuKQR5JBQpHmyOWE6bPRBZp
