sudo: required
services:
  - docker

language: node_js

env:
  - CXX=g++-4.8

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8


node_js:
  - "7"

before_script:
  - npm cache clean
  - npm install
  - npm install -g reaction-cli
  - sudo apt-get install docker.io
  - curl https://install.meteor.com/ | sh
  - sudo chown travis -Rh /home/travis/.config /home/travis/build
  - sudo meteor npm install
  - sudo chown travis -Rh .meteor/local
  - meteor update --release 1.5.1
  - sudo meteor npm install --save babel-core@latest babel-loader@latest


script:
  - reaction test

branches:

  only:

  - master

  - dev


deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU"
  on: master

notifications:
  slack: olgaverkkokauppa:VyuKQR5JBQpHmyOWE6bPRBZp
