sudo: required
language: node_js

node_js:
  - "7"

before_script:
  - npm install
  - npm install -g reaction-cli
  - curl https://install.meteor.com/ | sh
  - sudo chown travis -Rh /home/travis/.config /home/travis/build
  - sudo chown travis -Rh .meteor/local
  - sudo chown -R $USER:$GROUP ~/.npm
  - sudo meteor npm install
  - meteor update --release 1.5.1


script:
  - reaction test

branches:

  only:

  - master

  - dev

notifications:
  slack: olgaverkkokauppa:VyuKQR5JBQpHmyOWE6bPRBZp
